#!/bin/bash

cmd=$*

# 判断指令是否为空
if [ ! -n "$cmd" ]
then
        echo "command can not be null !"
        exit
fi

while getopts f: OPT;
do
    case $OPT in
        f|+f)
            files="$OPTARG $files"
            ;;
        *)
            echo "usage: `basename $0` [-f hostfile] <from> <to>"
            exit 2
    esac
done
shift `expr $OPTIND - 1`

if [ "" = "$files" ];
then
    echo "usage: `basename $0` [-f hostfile] <from> <to>"
    exit
fi

for file in $files
do
    if [ ! -f "$file" ];
    then
        echo "no hostlist file:$file"
        exit
fi
hosts="$hosts `cat $file`"
done

# 获取当前登录用户
user=`whoami`

# 在从机执行指令,这里需要根据你具体的集群情况配置，host与具体主机名一致，同上
#for (( host=1;host<=3;host++ ))
#do
#        echo "================current host is node0$host================="
#        echo "--> excute command \"$cmd\""
#        ssh $user@node0$host $cmd
#done

for host in $hosts;
do
    echo "xcall doing $host"
    echo "exec command :[ \"$cmd\"]"
    ssh $user@$host $cmd
    echo "xcall done $host"
done

echo "excute successfully !"
