#!/bin/bash
while getopts f: OPT;
do
    case $OPT in
        f|+f)
            files="$OPTARG $files"
            ;;
        *)
            echo "usage: `basename $0` [-f hostfile] <from> <to>"
            exit 2
    esac
done
shift `expr $OPTIND - 1`
 
if [ "" = "$files" ];
then
    echo "usage: `basename $0` [-f hostfile] <from> <to>"
    exit
fi
 
for file in $files
do
    if [ ! -f "$file" ];
    then
        echo "no hostlist file:$file"
        exit
fi
hosts="$hosts `cat $file`"
done

#2 获取文件名称
p1=$1
fname=$(basename $p1)
echo fname=$fname

#3 获取上级目录到绝对路径
#pdir=$(d -P $(dirname $p1); pwd)
pdir=$(cd -P $(dirname $p1); pwd)
echo pdir=$pdir

#4 获取当前用户名称
user=$(whoami)
echo user=$user
for host in $hosts;
do
    echo "doing $host"
    #scp $1 root@$host:$2
    #rsync -rvl --progress $1 $user@$host:$2
    echo "exec command :[rsync -rvl --progress $pdir/$fname $user@$host:$pdir]"
    rsync -rvl --progress $pdir/$fname $user@$host:$pdir
    echo "done $host"  
done
